config/routes.rb
HabitWatch::Application.routes.draw do
  authenticated :user do
    root :to => 'habits#index'
  end
  root :to => "home#index"
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: 'registrations'
  }

  devise_scope :user do
    get '/signup' => 'devise/registrations#new', :as => 'signup'
    get '/login' => 'devise/sessions#new', :as => 'login'
    delete '/logout' => 'devise/sessions#destroy', :as => 'logout'
    get '/settings' => 'devise/registrations#edit', :as => 'settings'

  end

  resources :habits
  match '/habits/:id/count' => 'habits#add_count', :as => 'add_count'


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/count.rb
class Count < ActiveRecord::Base
  attr_accessible :habit_id
  belongs_to :habit
  validates :habit_id, presence: true
end

app/models/habit.rb
class Habit < ActiveRecord::Base
  attr_accessible :name, :description, :type_of_habit

  validates :name, presence: true

  has_many :counts
  belongs_to :user

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :habits


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params={})
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    update_attributes(params)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/counts_controller.rb
class CountsController < ApplicationController

end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @habits = Habit.all
  end

  def show
    @habit = Habit.find(params[:id])
    # count = Count.create!(habit_id: @habit.id)
    # redirect_to habits_url
  end

  def new
    @habit = Habit.new
  end

  def edit
    @habit = Habit.find(params[:id])
  end

  def create
    @habit = Habit.new(params[:habit])

    if @habit.save
      redirect_to habits_path, notice: 'Habit added successfully.'
    else
      render action: "new"
    end

  end

  def update
    @habit = Habit.find(params[:id])

    if @habit.update_attributes(params[:habit])
      redirect_to habits_path, notice: 'Habit updated successfully.'
    else
      render action: "edit"
    end

  end

  def destroy
    @habit = Habit.find(params[:id])
    @habit.destroy
    redirect_to habits_url
  end

  def add_count
    @habit = Habit.find(params[:id])
    count = Count.create!(habit_id: @habit.id)
    redirect_to :back, notice: 'Activity recorded.'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  alias_method :facebook, :all
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(resource)
    settings_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/views/habits/_form.html.haml
= simple_form_for(@habit) do |f|
  = f.error_notification
  = f.input :name
  = f.input :description
  = f.input :type_of_habit, collection: ['good', 'bad', 'nuetral'], as: :radio_buttons
  = f.submit 'Submit', :class => 'btn btn-custom btn-small'

app/views/habits/edit.html.haml
.row
  .container
    %h1 Editing habit
    = render 'form'
    = link_to 'Show', @habit
    \|
    = link_to 'Back', habits_path

app/views/habits/index.html.haml
:javascript
  var g1, g2, g3;

  window.onload = function(){
    var g1 = new JustGage({
      id: "justgage_one", 
      value: $("#justgage_one").data("value"), 
      min: 0,
      max: 100,
      title: "Habit 1",
      label: "Good",
      levelColorsGradient: false
    });

    var g2 = new JustGage({
      id: "justgage_two", 
      value: getRandomInt(34, 65),
      min: 0,
      max: 100,
      title: "Habit 2",
      label: "Neutral",
      levelColorsGradient: false
    });

    var g3 = new JustGage({
      id: "justgage_three", 
      value: getRandomInt(66, 100), 
      min: 0,
      max: 100,
      title: "Habit 3",
      label: "Bad",
      levelColorsGradient: false
    });

  };
#gages
  .row
    .right
      = link_to 'Add a Habit', new_habit_path, :class => 'btn btn-inverse'
  .row
    .container
      .span3.gage_one
        #justgage_one{"data-value" => @habits.first.counts.count, :style => "width:300px;height:240px;padding: 0px;margin: 0px auto;"}
        .row
          .span3
            -if @habits.any?
              %table.table.table-bordered.table-striped.table-condensed.center
                %tr
                  %th Name
                  %th Count
                  %th Type
                  %th
                  - @habits.each do |habit|
                    %tr
                      %td= "#{habit.name}"
                      %td= "#{habit.counts.count}"
                      %td= "#{habit.type_of_habit}"
                      %td= link_to '+', add_count_path(habit), :class => 'btn btn-success'
                      %td= link_to 'Details', habit
                      %td= link_to 'Edit', edit_habit_path(habit)
            -else
              %p You haven't added any habits yet.
      .span3.gage_two
        #justgage_two{:style => "width:300px;height:240px;padding: 0px;margin: 0px auto;"}
        .row
          .span3
            -if @habits.any?
              %table.table.table-bordered.table-striped.table-condensed.center
                %tr
                  %th Name
                  %th Count
                  %th Type
                  %th
                  - @habits.each do |habit|
                    %tr
                      %td= "#{habit.name}"
                      %td= "#{habit.counts.count}"
                      %td= "#{habit.type_of_habit}"
                      %td= link_to '+', add_count_path(habit), :class => 'btn btn-success'
                      %td= link_to 'Details', habit
                      %td= link_to 'Edit', edit_habit_path(habit)
            -else
              %p You haven't added any habits yet.
      .span3.gage_three
        #justgage_three{:style => "width:300px;height:240px;padding: 0px;margin: 0px auto;"}
        .row
          .span3
            -if @habits.any?
              %table.table.table-bordered.table-striped.table-condensed.center
                %tr
                  %th Name
                  %th Count
                  %th Type
                  %th
                  - @habits.each do |habit|
                    %tr
                      %td= "#{habit.name}"
                      %td= "#{habit.counts.count}"
                      %td= "#{habit.type_of_habit}"
                      %td= link_to '+', add_count_path(habit), :class => 'btn btn-success'
                      %td= link_to 'Details', habit
                      %td= link_to 'Edit', edit_habit_path(habit)
            -else
              %p You haven't added any habits yet.
:javascript
  $(document).ready(function() {
    $("#justgage_one td a").on('click', function(event) {
      $.post(#{add_count_path(@habits.first)}, function(data) {
        g1.refresh(data.value)
      })
      event.preventDefault()
    })
  })

app/views/habits/new.html.haml
.row
  .container
    %h3 Add a Habit
    = render 'form'

app/views/habits/show.html.haml
.span12
%table.table.table-bordered.table-striped
  %tr
    %th Name
    %th Count
    %th Description
    %th Type
    %th Today
    %th Last 7 Days
    %th Last Month
    %th Last Year

  %tr
    %td= @habit.name
    %td= @habit.counts.count
    %td= @habit.description
    %td= @habit.type_of_habit
    %td= @habit.counts.where(:created_at => (Time.now.at_beginning_of_day.utc..Time.now.utc)).count
    %td= @habit.counts.where(:created_at => (7.days.ago.utc..Time.now.utc)).count
    %td= @habit.counts.where(:created_at => (1.month.ago.utc..Time.now.utc)).count
    %td= @habit.counts.where(:created_at => (1.year.ago.utc..Time.now.utc)).count


= link_to 'Edit', edit_habit_path(@habit), class: 'btn btn-info'
= link_to 'Delete', @habit, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/home/index.html.haml
.container=image_tag 'http://placehold.it/1000x400&text=[img]'

app/views/layouts/_footer.html.haml
.container
  .row
    %ul.inline-list.right
      %li
        = link_to "Habit Watch", root_path
    %p &copy; Copyright 2013. Habit Technologies, LLC

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-custom
  .navbar-inner
    .container
      .brand
        =link_to(image_tag("logo.png", :alt =>  "Habit Watch"), root_path) 
      %ul
        - if user_signed_in?
          %li
            = link_to 'Logout', logout_path, :method=>'delete', class: 'btn btn-custom btn-small'
        - else
          %li
            = link_to 'Login', login_path, class: 'btn btn-custom btn-small'
        - if user_signed_in?
          %li
            = link_to 'Settings', settings_path, class: 'btn btn-custom btn-small'
        - else
          %li.sign-up
            = link_to 'Sign up', signup_path, class: 'btn btn-custom btn-small'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Habit Watch"
      %meta{:content => content_for?(:description) ? yield(:description) : "Habit Watch", :name => "description"}
        = javascript_include_tag 'justgage.1.0.1.min.js'
        = javascript_include_tag 'raphael-min.js'
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .row
      %header
        = render 'layouts/navigation'
      .container
        = render 'layouts/messages'
    .row
      .container
        = yield
    %footer
      = render 'layouts/footer'

app/views/prototypes/graph.haml
#graph
#debug
  = @dataset
%script{src: "http://d3js.org/d3.v3.min.js"}
%script{:type => "text/javascript"}
  // data that you want to plot, I've used separate arrays for x and y values
  var xdata = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24], ydata = [#{@dataset.join(",")}];

  // size and margins for the chart
  var margin = {top: 20, right: 15, bottom: 60, left: 60}, width = 960 - margin.left - margin.right, height = 500 - margin.top - margin.bottom;

  // x and y scales, I've used linear here but there are other options
  // the scales translate data values to pixel values for you
  var x = d3.scale.linear().domain([0, d3.max(xdata)]).range([ 0, width ]);        // the pixel range of the x-axis

  var y = d3.scale.linear().domain([0, d3.max(ydata)]).range([ height, 0 ]);

  // the chart object, includes all margins
  var chart = d3.select('#graph').append('svg:svg').attr('width', width + margin.right + margin.left).attr('height', height + margin.top + margin.bottom).attr('class', 'chart')

  // the main object where the chart and axis will be drawn
  var main = chart.append('g').attr('transform', 'translate(' + margin.left + ',' + margin.top + ')').attr('width', width).attr('height', height).attr('class', 'main')

  // draw the x axis
  var xAxis = d3.svg.axis().scale(x).orient('bottom');

  main.append('g').attr('transform', 'translate(0,' + height + ')').attr('class', 'main axis date').call(xAxis);

  // draw the y axis
  var yAxis = d3.svg.axis().scale(y).orient('left');

  main.append('g').attr('transform', 'translate(0,0)').attr('class', 'main axis date').call(yAxis);

  // draw the graph object
  var g = main.append("svg:g");

  g.selectAll("scatter-dots").data(ydata).enter().append("svg:circle").attr("cy", function (d) { return y(d); } ).attr("cx", function (d,i) { return x(xdata[i]); } ).attr("r", 10).style("opacity", 0.6);

app/views/prototypes/watch.haml
%button#button THE BUTTON
%button#sync Sync

#status
  %strong Databased Counts:
  %span#database #{@counts_db}
  %br
  %strong Unsyncronized Counts:
  %span#local